apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opentakrouter.fullname" . }}-config
  labels:
    {{- include "opentakrouter.labels" . | nindent 4 }}
data:
  opentakrouter.json: |
    {
      "AllowedHosts": "*",
      "server": {
        "persist_messages": {{ .Values.config.persistMessages }},
        "public_endpoint": {{ .Values.config.publicEndpoint | quote }},
        "storage": {
          "provider": {{ .Values.storage.provider | quote }},
          "sqlite": {
            "path": {{ .Values.storage.sqlite.path | quote }}
          },
          "postgres": {
            "connectionString": {{ .Values.storage.postgres.connectionString | quote }}
          }
        },
        "provisioning": {
          "packageName": {{ .Values.provisioning.packageName | quote }},
          "serverDescription": {{ .Values.provisioning.serverDescription | quote }},
          "publicApiScheme": {{ include "opentakrouter.publicApiScheme" . | quote }},
          "publicApiPort": {{ include "opentakrouter.publicApiPort" . }},
          "trustStoreCertificate": {{ printf "%s/%s" .Values.provisioning.mountPath .Values.provisioning.trustStore.fileName | quote }},
          "trustStorePassword": {{ include "opentakrouter.provisioningTrustStorePassword" . | quote }},
          "clientCertificate": {{ printf "%s/%s" .Values.provisioning.mountPath .Values.provisioning.clientCertificate.fileName | quote }},
          "clientCertificatePassword": {{ include "opentakrouter.provisioningClientCertificatePassword" . | quote }},
          "onReceiveDelete": true
        },
        "api": {
          "enabled": {{ .Values.config.api.enabled }},
          "port": {{ .Values.service.apiPort }},
          "swagger": {{ .Values.config.api.swagger }},
          "ssl": {{ .Values.config.api.ssl }},
          "cert": {{ printf "%s/%s" .Values.tls.mountPath .Values.tls.certFile | quote }},
          "key": {{ printf "%s/%s" .Values.tls.mountPath .Values.tls.keyFile | quote }},
          "passphrase": ""
        },
        "websockets": {
          "enabled": {{ .Values.config.websockets.enabled }},
          "port": {{ .Values.service.websocketPort }},
          "ssl": {{ .Values.config.websockets.ssl }},
          "cert": {{ printf "%s/%s" .Values.tls.mountPath .Values.tls.certFile | quote }},
          "key": {{ printf "%s/%s" .Values.tls.mountPath .Values.tls.keyFile | quote }},
          "passphrase": ""
        },
        "links": {{ toJson .Values.config.links }},
        "routing": {{ toJson .Values.config.routing }}
      }
    }
