{{- if and .Values.provisioning.enabled .Values.provisioning.clientCertificate.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opentakrouter.provisioningClientSecretName" . }}
  labels:
    {{- include "opentakrouter.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.provisioning.clientCertificate.secretKey }}: {{ required "provisioning.clientCertificate.data is required when provisioning.clientCertificate.create=true" .Values.provisioning.clientCertificate.data | quote }}
{{- end }}
