apiVersion: v1
kind: Service
metadata:
  name: {{ include "opentakrouter.fullname" . }}
  labels:
    {{- include "opentakrouter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "opentakrouter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    {{- if .Values.config.api.enabled }}
    - name: http
      port: {{ .Values.service.apiPort }}
      targetPort: http
    {{- end }}
    {{- if .Values.config.websockets.enabled }}
    - name: websocket
      port: {{ .Values.service.websocketPort }}
      targetPort: websocket
    {{- end }}
    {{- range .Values.config.links }}
    {{- if and .enabled (eq .role "listen") (eq .transport "tcp") }}
    - name: tak-tcp
      port: {{ .port }}
      targetPort: tak-tcp
    {{- end }}
    {{- if and .enabled (eq .role "listen") (eq .transport "tls") }}
    - name: tak-tls
      port: {{ .port }}
      targetPort: tak-tls
    {{- end }}
    {{- end }}
